export const GET_PROJECT_COLLECTION = 'app/ProjectPage/GET_PROJECT_COLLECTION';
export const GET_PROJECT_COLLECTION_SUCCESS = 'app/ProjectPage/GET_PROJECT_COLLECTION_SUCCESS';
export const GET_PROJECT_COLLECTION_FAILURE = 'app/ProjectPage/GET_PROJECT_COLLECTION_FAILURE';

export const GET_PROJECT_LIST = 'app/ProjectPage/GET_PROJECT_LIST';
export const GET_PROJECT_LIST_SUCCESS = 'app/ProjectPage/GET_PROJECT_LIST_SUCCESS';
export const GET_PROJECT_LIST_FAILURE = 'app/ProjectPage/GET_PROJECT_LIST_FAILURE';

export const CREATE_PROJECT = 'app/ProjectPage/CREATE_PROJECT';
export const CREATE_PROJECT_SUCCESS = 'app/ProjectPage/CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILURE = 'app/ProjectPage/CREATE_PROJECT_FAILURE';